# Generated by Django 6.0.2 on 2026-04-02 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lessonprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='compressed_video_size',
            field=models.PositiveIntegerField(blank=True, help_text='Siqilgan hajm (bayt)', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_video_compressed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='original_video_size',
            field=models.PositiveIntegerField(blank=True, help_text='Original hajm (bayt)', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_duration',
            field=models.CharField(blank=True, help_text='Video davomiyligi (HH:MM:SS)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_thumbnail',
            field=models.ImageField(blank=True, help_text='Avtomatik yaratiladi', null=True, upload_to='lesson_thumbnails/'),
        ),
    ]
